### ISSUE TITLE
snapshot parse errors

### ISSUE THREAD

**Issue by davecarlson** [styled-components/jest-styled-components#55]
It seems the new 2+ versions of this package are snapshotting incorrectly ( just a load of c0 etc )

Tests: 
```
import React from 'react'
import renderer from 'react-test-renderer'
import withTheme from '~/config/jest/jestTheme'
import 'jest-enzyme'
import 'jest-styled-components'
import { mount } from 'enzyme'

import { CardTitle } from '../'

describe('Component: Card Title', () => {
  it('should render without props.route', () => {
    let component = withTheme(<CardTitle title="title testing" />)

    const tree = renderer.create(component).toJSON()
    expect(tree).toMatchSnapshot()
  })

  it('should render the Link if props.href is supplied or inherited', () => {
    const component = mount(
      withTheme(<CardTitle href="/link" title="title testing" />)
    )

    expect(component.find('Link').length).toBe(1)
  })
})
```

Snapshot created: 
```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`Component: Card Title should render without props.route 1`] = `
c0.c0bc0pc0Dc0Oc0ec0Uc0 c0{c0
c0 c0 c0fc0oc0nc0tc0-c0wc0ec0ic0gc0hc0tc0:c0 c0bc0oc0lc0dc0;c0
c0 c0 c0lc0ic0nc0ec0-c0hc0ec0ic0gc0hc0tc0:c0 c01c0.c03c0;c0
c0 c0 c0fc0oc0nc0tc0-c0sc0ic0zc0ec0:c0 c01c06c0pc0xc0;c0
c0 c0 c0cc0oc0lc0oc0rc0:c0 c0#c0fc0fc0fc0fc0fc0fc0;c0
c0}c0
c0
c0<c0dc0ic0vc0
c0 c0 c0cc0lc0ac0sc0sc0Nc0ac0mc0ec0=c0"c0cc0ac0rc0dc0-c0tc0ic0tc0lc0ec0 c0 c0dc03c0qc01c0yc07c0-c00c0 c0bc0pc0Dc0Oc0ec0Uc0"c0
c0>c0
c0 c0 c0tc0ic0tc0lc0ec0 c0tc0ec0sc0tc0ic0nc0gc0
c0<c0/c0dc0ic0vc0>c0
`;
```

Component:
```
import React from 'react'
import { string, node, bool } from 'prop-types'
import LinkAnchor from '~/components/LinkAnchor'

import StyledCardHeader from './CardHeader.styles'

const CardHeader = props => {
  let header = (
    <StyledCardHeader
      href={props.href}
      src={props.src}
      top={props.top}
      bottom={props.bottom}
      height={props.height}>
      {props.children}
    </StyledCardHeader>
  )

  if (props.href) {
    header = (
      <LinkAnchor href={props.href}>
        {header}
      </LinkAnchor>
    )
  }

  return header
}

CardHeader.propTypes = {
  href: string,
  src: string,
  height: string,
  top: bool,
  bottom: bool,
  children: node
}

CardHeader.defaultProps = {
  top: false,
  bottom: false
}

export default CardHeader
```

Styles: 
```
import styled from 'styled-components'

const StyledCardHeader = styled.header`
  background-repeat: no-repeat;
  background-position: center center;
  background-color: ${props => props.theme.colors.itemBackground};
  background-size: cover;

  ${props =>
    props.src &&
    `
    background-image: url('${props.src}');
    min-height: ${props.height || '200px'};
    `};

  display: flex;
  flex-direction: column;
  align-items: flex-start;
  justify-content: ${props => (props.bottom ? 'flex-end' : 'flex-start')};
  padding: ${props => props.theme.grid.quarterSpacing};
  color: ${props => props.theme.colors.white};
`

export default StyledCardHeader

```

**Comment by davecarlson** [comment]
It seems to be something to with passing classname. If I remove: 
```className={`card-title ${className}`}```, then it snapshots correctly.

**Comment by MicheleBertoli** [comment]
Hello @davecarlson, thanks for opening this issue.
Are you using 4.2.1? I fixed a similar issue just [yesterday](https://github.com/styled-components/jest-styled-components/blob/master/CHANGELOG.md#421---2017-07-23).
Please let me know, otherwise I'll be happy to look into it.

**Comment by davecarlson** [comment]
```4.2.0```, I'll check with 4.2.1 now :)

**Comment by davecarlson** [comment]
Nope, still the same. 

Here's a simpler component that it happens on: 

```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`Component: Content should render 1`] = `
c0<c0dc0ic0vc0
c0 c0 c0cc0lc0ac0sc0sc0Nc0ac0mc0ec0=c0"c0 c0cc0oc0nc0tc0ec0nc0tc0"c0
c0>c0
c0 c0 c0<c0sc0pc0ac0nc0>c0
c0 c0 c0 c0 c0Tc0ec0sc0tc0 c0Cc0oc0nc0tc0ec0nc0tc0
c0 c0 c0<c0/c0sc0pc0ac0nc0>c0
c0<c0/c0dc0ic0vc0>c0
`;
```

```
import React from 'react'
import { oneOfType, string, object, element, array } from 'prop-types'

const Content = ({ children, className }) =>
  <div className={`${className} content`}>
    {children}
  </div>

Content.propTypes = {
  className: string,
  children: oneOfType([object, element, array]).isRequired
}

Content.defaultProps = {
  className: ''
}

export default Content
```

```
import React from 'react'
let { describe, it, expect } = global
import 'jest-enzyme'

import { mount } from 'enzyme'
import Content from '../'

import 'jest-styled-components'
import renderer from 'react-test-renderer'


describe('Component: Content', () => {
  it('should render', () => {
    let component = (
      <Content>
        <span>Test Content</span>
      </Content>
    )

    const tree = renderer.create(component).toJSON()

    expect(tree).toMatchSnapshot()

    const componentHTML = mount(component).html()

    expect(componentHTML).toContain('><span>Test Content</span>')
  })
})
```

**Comment by davecarlson** [comment]
I can update my code to use the  `classnames` package, but I think there's a small issue in the pattern matcher that's causing this ( and probably for other people too ) - I only noticed it when I came to update a component & saw the old snap

**Comment by MicheleBertoli** [comment]
Awesome, thank you very much for the useful information @davecarlson.
This is fixed in 4.2.2.
